version: "3.4"

volumes:
    node_modules:
        driver: local
    pg_data:
        driver: local
    pgadmin:
        driver: local

services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: unless-stopped

  front:
    build: ./uslugi-front
    command: ["yarn", "start"]
    stdin_open: true
    volumes:
      - ./uslugi-front:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - init
    restart: unless-stopped

  server:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./uslugi-svr:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
      - npm

  postgres:
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
        - 5432:5432

  php:
    build: ./uslugi-svr
    volumes:
      - ./uslugi-svr:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
        - init
    restart: unless-stopped

  composer:
    image: composer:latest
    volumes:
      - ./uslugi-svr:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer', 'install']
    restart: on-failure

  npm:
    image: node:13.7
    volumes:
      - ./uslugi-svr:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', 'install']
    restart: on-failure

  init:
    build: ./uslugi-svr
    volumes:
      - ./uslugi-svr:/var/www/html
      - ./:/init
    depends_on:
      - postgres
      - composer
    working_dir: /var/www/html
    env_file: ./uslugi-svr/.env.example
    command: ['sh', '/init/init.sh']
    restart: 'no'

  artisan:
    build: ./uslugi-svr
    volumes:
      - ./uslugi-svr:/var/www/html
    depends_on:
      - postgres
      - composer
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    restart: 'no'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pg@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
