version: "3.4"

volumes:
  node_modules:
    driver: local

services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  front:
    build: ./uslugi-front
    command: ["yarn", "start"]
    stdin_open: true
    volumes:
      - ./uslugi-front:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  server:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./uslugi-svr:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./uslugi-svr:/var/www/html
    ports:
      - "9000:9000"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./uslugi-svr:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer', 'install']

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./uslugi-svr:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', 'install']
